language: cpp
dist: xenial
os: linux

matrix:
  include:
    - compiler: "gcc"
      env: PPSSPP_BUILD_TYPE=Linux PVS_ANALYZE=Yes
    - compiler: "clang"
      env: PPSSPP_BUILD_TYPE=Linux
      
script:
  - bash travis_script.sh

